version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
      - ME_CONFIG_MONGODB_SERVER=mongodb


