version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sgt2023
      MYSQL_DATABASE: db
      MYSQL_USER: Evija
      MYSQL_PASSWORD: sgt2023
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      mysql-network:
        aliases:
          - mysql
  python:
    build: .
    container_name: python
    restart: always
    depends_on:
      - mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local



